wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1691577259.418782
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 83
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 83
      3:
      - 19
      - 23
      4: 3.10.12
      5: 0.15.8
      6: 4.31.0
      8:
      - 1
      - 5
stable_diffusion_checkpoint:
  desc: null
  value: stabilityai/stable-diffusion-xl-base-1.0
refiner_checkpoint:
  desc: null
  value: stabilityai/stable-diffusion-xl-refiner-1.0
offload_to_cpu:
  desc: null
  value: false
compile_model:
  desc: null
  value: false
prompt_1:
  desc: null
  value: UML class diagram showcasing the composition relationship between 'Car' and
    'Engine', where 'Car' is composed of 'Engine'. Use standard UML symbols for composition.
prompt_2:
  desc: null
  value: Illustrate a UML diagram where the 'Car' class has a composition relationship
    with the 'Engine' class, signifying that a car contains an engine.
negative_prompt_1:
  desc: null
  value: inheritance, aggregation relationships in the diagram.
negative_prompt_2:
  desc: null
  value: Avoid including any additional classes or relationships other than 'Car'
    and 'Engine' with the composition relationship.
seed:
  desc: null
  value: null
use_ensemble_of_experts:
  desc: null
  value: false
num_inference_steps:
  desc: null
  value: 100
num_refinement_steps:
  desc: null
  value: 150
high_noise_fraction:
  desc: null
  value: 0.8
scheduler_kwargs:
  desc: null
  value:
    beta_end: 0.012
    beta_schedule: scaled_linear
    beta_start: 0.00085
    interpolation_type: linear
    num_train_timesteps: 1000
    prediction_type: epsilon
    steps_offset: 1
    timestep_spacing: leading
    trained_betas: null
    use_karras_sigmas: false
prompt_credits:
  desc: null
  value: ''
