wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1691476453.296629
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 83
      3:
      - 23
      4: 3.10.12
      5: 0.15.8
      6: 4.31.0
      8:
      - 1
      - 5
